# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7df4b33652ee75aafda03b0a6392965711178c57ef96fd28aff6d2590035304123a9ab26f6e74ca75a2c9ae903e6189a6db4a472af1a0b0a51d113ff650714d0
  github: 
    :oauth2_client_id: 878133690aa3500e89f5
    :oauth2_client_secret: 695d02a9c3ace281d198d668b0ad70ce4a99d0fb
test:
  secret_key_base: 7ef59b8b7727a7df45e84a0936f5844f31043dba42c0da5024c1e7a56a9c4d4d40860ce309ce2f0db76402f1de7962eeba05307faf8dae1b533c6b45870d8fcc
  github: 
    :oauth2_client_id: 45645dfgg645
    :oauth2_client_secret: 695d02a9c3a45656ce281d198d668b0ad70ce4a99d0fb
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
